;;;; Hockey Oracle package definitions

(in-package :cl-user)

(defpackage :hockey-oracle.core
  (:use :alexandria :cl :glu :local-time :redis :split-sequence)
  (:documentation "Hockey Oracle core domain.")
  (:export
   :app
   :make-app
   :app-base-dir
   :app-updated
   :app-version
   :*app*
   :random-string
   :gen-hash
   :pretty-time
   :league
   :make-league
   :league-id
   :league-name
   :league-full-name
   :league-created
   :league-active?
   :league-game-reminder-day-offset
   :league-game-reminder-time
   :league-send-automated-emails?
   :league-commissioner-ids
   :league-active-player-ids
   :league-inactive-player-ids
   :get-all-leagues
   :get-league
   :update-league
   :season
   :make-season
   :season-id
   :season-name
   :season-start-date
   :season-end-date
   :get-seasons
   :game
   :game-id
   :game-created-at
   :game-created-by
   :game-notes
   :game-time
   :game-progress
   :game-home-team
   :game-away-team
   :game-home-score
   :game-away-score
   :game-progress-states
   :game-email-reminder
   :game-confirms
   :game-league
   :game-chat-id
   :get-game
   :get-games
   :get-upcoming-games
   :save-new-game
   :cancel-game
   :delete-game
   :update-game-info
   :confirm-types
   :game-confirm
   :game-confirm-reason-max-length
   :make-game-confirm
   :game-confirm-player
   :game-confirm-time
   :game-confirm-confirm-type
   :game-confirm-reason
   :game-confirm-for
   :confirmed-players
   :unconfirmed-players
   :save-game-confirm
   :message
   :message-player-id
   :message-created-at
   :message-updated-at
   :message-msg
   :message-max-length
   :make-message
   :get-chat
   :save-message-new
   :player
   :make-player
   :player-id
   :player-name
   :player-admin?
   :player-notify-on-player-status-change?
   :player-email
   :player-auth
   :player-perm-auth
   :player-temp-auth
   :player-salt
   :player-position
   :player-active?
   :player-activate
   :player-deactivate
   :players-positions
   :get-players
   :get-player
   :get-emailable-players
   :player-active-in?
   :player-member-of?
   :is-commissioner?
   :save-player-simple
   :save-player-active
   :change-player-pwd
   :reset-pwd-get-token
   :reset-pwd-set-token
   :team
   :make-team
   :team-id
   :team-name
   :team-logo
   :get-teams
   :get-team
   :server-info
   :server-info-host
   :get-server-info
   :send-email))

(defpackage :hockey-oracle.web
  (:use :alexandria :cl :cl-who :glu :hockey-oracle.core :hunchentoot :local-time
   :split-sequence)
  (:documentation "Hockey Oracle web interface.")
  (:export
   :web-app
   :start-server!
   :stop-server))
